### ISSUE TITLE
다운로드 오류

### ISSUE THREAD

**Issue by followme777** [OpenSourceConsulting/athena-meerkat#1]
https://github.com/OpenSourceConsulting/athena-meerkat/releases

athena-meerkat-commander-1.0.0-SNAPSHOT-bin.tar.gz
23.7 MBconsole.war
110 MBcontroller.war
27.5 KBdb_init_script.sql
46.8 MBdown.zip

여기서 1.0.0-beta.3 버전을 다운로드 받으려고 하는데... 계속 네트워크 오류가 납니다....다른곳에서 이 파일들을 다운로드 받을 수 는 없는지요???

**Comment by nices96** [comment]
답변이 늦어 죄송합니다. 현재 링크는 모두 정상적이며 다운로드 하려는 곳의 인터넷 환경과 영향이 있지 않나 싶습니다. 메일주소를 알려주시면 관련 파일을 메일로 보내드리도록 하겠습니다.
